version: '3'

services:
  mongodb:
    image: mongo:4.2.1-bionic
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
    volumes:
      - dbdata:/data/db
    networks:
      - magents-network

  api:
    depends_on:
      - mongodb
    build: .
    env_file:
      - ./.env
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - DB_HOST=mongodb
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_NAME=${MONGODB_DATABASE}
      - DB_PORT=${MONGODB_DOCKER_PORT}
    volumes:
      - .:/app
    networks:
      - magents-network

volumes:
  dbdata:


networks:
  magents-network:
    driver: bridge
